# Generated by Django 5.0.7 on 2024-07-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
